// templates/svelte-ts/src/lib/SampleComponent.svelte
<script lang="ts">
  import "./sample-component.css";

  /**
   * Is this the principal call to action on the page?
   */
  export let primary = false;

  /**
   * What background color to use
   */
  export let backgroundColor: string | undefined = undefined;
  /**
   * How large should the button be?
   */
  export let size: "small" | "medium" | "large" = "medium";
  /**
   * Button contents
   */
  export let label: string = "";

  $: mode = primary
    ? "storybook-button--primary"
    : "storybook-button--secondary";

  $: style = backgroundColor ? `background-color: ${backgroundColor}` : "";
</script>

<button
  type="button"
  class={["storybook-button", `storybook-button--${size}`, mode].join(" ")}
  {style}
  on:click
>
  {label}
</button>

// templates/react/src/components/SampleComponent/SampleComponent.jsx
import "./sampleComponent.css";
import PropTypes from 'prop-types'

export const SampleComponent = ({
  label,
  backgroundColor,
  primary = false,
  size = "medium",
  ...props
}) => {
  const mode = primary
    ? "storybook-button--primary"
    : "storybook-button--secondary";
  return (
    <button
      type="button"
      className={["storybook-button", `storybook-button--${size}`, mode].join(
        " "
      )}
      style={{ backgroundColor }}
      {...props}
    >
      {label}
    </button>
  );
};

SampleComponent.propTypes =  {
  primary: PropTypes.bool,
  size: PropTypes.string,
  backgroundColor: PropTypes.string,
  label: PropTypes.string
}
